### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by hrobeers** [ehsanMa86/NACA-4digits-m4#1]
This script is missing a license file.
I'd like to contribute, but I need to know my rights.

Thanks for sharing this!

**Comment by ehsanMa86** [comment]
@hrobeers
Hello Hans,

I didn't see your comment by now and for some reason github didn't notify me about it. Sorry for my very late reply. The license is GNU GPL3. It is written for OpenFOAM which itself stands for the GPL3 license as well. I am excited to have your contribution and thanks for your time doing it. IT definitely will improve it.

Best regards,
Ehsan

**Comment by hrobeers** [comment]
Cool thanks, I haven't been touching this in a while now. But when I find the time, I'll try to distill the interesting changes for a PR. My improvements were mainly focused on improving the skewness and boundary layer refinement.

I'm also looking at using a medial axis approach (based on voronoi diagrams) to define the block boundaries for improved skewness. But this will require a small C++ program to be added (not purely m4)

**Comment by ehsanMa86** [comment]
I am in! So excited. Those are actually good points to implement.  Please let me know if I could be helpful at any point. I am more than happy to do it. 

Thanks Hans
